# Book settings
title: Bayesian Analysis in Python (2nd ed.) with NumPyro
author: <a href="https://github.com/tallamjr/">Tarek Allam Jr. [Allam Labs.]</a>
copyright: ""
logo: "site/images/bap-cover.png"

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : ['helper_functions','Chapter_*',Chapter_Introduction/*','Chapter_OptimisationGoals/*','Chapter_MotivatingExample/Baseline*','Chapter_MotivatingExample/Sim*']  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#parse:
#  myst_extended_syntax: true
  myst_footnote_transition: False
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
#######################################################################################
# HTML-specific settings
html:
  favicon                   : "site/images/favicon.ico"  # A path to a favicon image
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://tallamjr.github.io/bap-numpyro/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false
  extra_footer: |
    <p>
    Code released under a <a href="https://opensource.org/licenses/MIT">MIT license</a>.
    </p>

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : https://colab.research.google.com # The URL of Google Colab (e.g., https://colab.research.google.com)

repository:
  url                       : https://github.com/tallamjr/bap-numpyro # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :   # A list of extra extensions to load by Sphinx.
    - jupyterbook_latex
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
    html_show_copyright: false
    html_static_path: ['_static']

# latex:
#   latex_documents:
    # targetname: <file.tex>

# bibtex_bibfiles:
#    - references.bib
