
name: bap-numpyro
channels:
  - conda-forge
  - defaults
dependencies:
  - nikola
  - pip
  - python=3.8
  - pip:
    - black
    - nbval
    - neovim
    - pep517
    - pytest
    - pytest-cov
    - pytest-subtests
    - twine
    - -r requirements.txt
