name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  chapters:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/pyro-ppl/numpyro.git
        pip install -r requirements.txt
        pip install nbval
    - name: Test with nbval
      run: |
        find notebooks -maxdepth 1 -name "[01][01234]*.ipynb" | grep -v "[01][01234]*-x.ipynb" | sort -n | xargs pytest -vx --nbval-lax --durations=0

  # chapters_exercises:

  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: [3.9]

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install git+https://github.com/pyro-ppl/numpyro.git
  #       pip install -r requirements.txt
  #       pip install nbval
  #   - name: Test with nbval
  #     run: |
  #       find notebooks -maxdepth 1 -name "[01][01234]*-x.ipynb" | grep -v "[01][012345678]*.ipynb" | sort -n | xargs pytest -vx --nbval-lax --durations=0

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
  # deploy-book:
  #   needs: [chapters, chapters_exercises]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2

  #   # Install dependencies
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.8

  #   - name: Install dependencies
  #     run: |
  #       pip install -r requirements.txt

  #   # Build the book
  #   - name: Build the book
  #     run: |
  #       jupyter-book build .

  #   # Push the book's HTML to github-pages
  #   - name: GitHub Pages action
  #     uses: peaceiris/actions-gh-pages@v3.6.1
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: ./_build/html
